[package]
name = "payload-packer"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Pack UEFI FD / kernel payloads into whyred-flashable boot.img"

[dependencies]
bootimg-rs = { path = "../bootimg-rs" }
clap = { version = "4", features = ["derive"] }

[[bin]]
name = "payload-packer"
path = "src/main.rs"
